<?php
return [
    'age_group' => [
        '18-20',
        '21-30',
        '31-40',
        '41-50',
    ],
    'backhome_city' => [
        'Maulvibazar',
        'Non-Sylheti',
        'Sunamganj',
        'Sylhet',
        'Hajiganj',
    ],
    'citizenship' => [
        'British Citizen',
        'Indefinite Leave to Remain',
        'Non-British',
    ],
    'disability' => [
        'No',
        'Yes',
    ],
    'education_qualification' => [
        'A Level',
        'Doctorate Degree',
        'Madrasah Education',
        'Non-Degree Qualification',
        'Postgraduate Degree',
        'Secondary School',
        'Undergraduate Degree',
        'Other',
    ],
    'figure' => [
        'Average',
        'Fatty',
        'Healthy',
        'Medium',
        'Slim',
    ],
    'gender' => [
        'Female',
        'Male',
    ],
    'house_type' => [
        'Council property',
        'Own property',
        'Rented property',
    ],
    'height' => [
        '4’0’’-4’6’’',
        '4’7’’-5’3’’',
        '5’4’’-6’0’’',
        '6’1’’-6’5’’',
    ],
    'has_driving_license' => [
        'No',
        'Yes',
    ],
    'knows_cooking' => [
        'I am learning cooking & will cook at my in-law’s house',
        'I know cooking but am not an expert',
        'I don’t know cooking at all',
        'Yes, I am a professional chef',
    ],
    'language' => [
        'English & Proper Bengali',
        'English & Sylheti',
        'Only English',
    ],
    'marital_status' => [
        'Divorced with kid',
        'Divorced with no kid',
        'Never married',
        'Widowed',
    ],
    'marriage_intentions' => [
        'Ready for marriage',
        'Within 1 year',
        'Within 3 months',
        'Within 6 months',
    ],
    'parents_status' => [
        'Both Alive',
        'Both Dead',
        'Separated',
        'Single Alive',
    ],
    'profession' => [
        'Alim',
        'Accountant',
        'Army',
        'Banker',
        'Barrister',
        'Beautician',
        'Business owner',
        'Chef',
        'Compliance officer',
        'Customer service advisor',
        'Designer',
        'Dentist',
        'Doctor',
        'Delivery Driver',
        'Engineer',
        'Event manager',
        'Factory worker',
        'Government employee',
        'Imam',
        'IT sector employee',
        'Lecturer',
        'Lawyer',
        'Manager',
        'Medical professional',
        'NHS',
        'Nurse',
        'Optician',
        'Pharmacist',
        'Pilot',
        'Plumber',
        'Professor',
        'Retail employee',
        'Remote work',
        'Sales assistant',
        'Self-employed',
        'Sportsman',
        'Taxi driver',
        'Teacher',
        'Waiter',
        'Warehouse worker',
        'Other',
    ],
    'region' => [
        'East Midlands',
        'East of England',
        'Greater London',
        'North East',
        'North West',
        'South East',
        'South West',
        'West Midlands',
        'Wales',
        'Yorkshire and The Humber',
    ],
    'religious_mazhab' => [
        'Hanafi',
        'Hanbali',
        'Maliki',
        'Shafi',
    ],
    'religious_practice' => [
        'Not practising',
        'Moderately practising',
        'Very religious',
    ],
    'salary_range' => [
        '£100,000+',
        '£5,000 - £10,000',
        '£10,001 - £15,000',
        '£15,001 - £20,000',
        '£20,001 - £25,000',
        '£25,001 - £30,000',
        '£30,001 - £35,000',
        '£35,001 - £40,000',
        '£40,001 - £45,000',
        '£45,001 - £50,000',
        '£50,001 - £100,000',
    ],
    'skin_colour' => [
        'Brown',
        'Dark',
        'Fair',
        'Light Brown',
        'Light Dark',
        'Very Fair',
    ],
    'smoking' => [
        'Non-smoker',
        'Smoker',
    ],
    'spouse_age_preference' => [
        '18-50',
    ],
    'spouse_citizenship' => [
        'British Citizen',
        'Indefinite Leave to Remain',
        'Non-British',
    ],
    'spouse_consider_divorce' => [
        'No',
        'Yes',
    ],
    'spouse_consider_divorce_with_children' => [
        'No',
        'Yes',
    ],
    'spouse_consider_non_uk_citizen' => [
        'No',
        'Yes',
    ],
    'spouse_consider_with_disabilities' => [
        'No',
        'Yes',
    ],
    'spouse_council' => [
        'Anywhere in the UK',
    ],
    'spouse_education_preference' => [
        'Doctorate Degree',
        'Doesn’t matter',
        'Madrasah education',
        'Non-Degree Qualification',
        'Postgraduate',
        'Secondary school',
        'A level',
        'Graduated',
    ],
    'spouse_height' => [
        'Doesn’t matter',
        'Minimum 4’-4’6’’',
        'Minimum 4’7’’-5’3’’',
        'Minimum 5’4’’-6’0’’',
        'Minimum 6’1’’-6’5’’',
    ],
    'spouse_marital_status' => [
        'Divorced with kid',
        'Divorced with no kid',
        'Never married',
        'Widowed',
    ],
    'spouse_occupation_preference' => [
        'Alim',
        'Accountant',
        'Army',
        'Banker',
        'Barrister',
        'Beautician',
        'Business owner',
        'Chef',
        'Compliance officer',
        'Customer service advisor',
        'Designer',
        'Dentist',
        'Doctor',
        'Delivery Driver',
        'Engineer',
        'Event manager',
        'Factory worker',
        'Government employee',
        'Imam',
        'IT sector employee',
        'Lecturer',
        'Lawyer',
        'Manager',
        'Medical professional',
        'NHS',
        'Nurse',
        'Optician',
        'Pharmacist',
        'Pilot',
        'Plumber',
        'Professor',
        'Retail employee',
        'Remote work',
        'Sales assistant',
        'Self-employed',
        'Sportsman',
        'Taxi driver',
        'Teacher',
        'Waiter',
        'Warehouse worker',
        'Other',
    ],
    'spouse_religious_dress_preference' => [
        'No',
        'Modest',
        'Yes',
    ],
    'spouse_skin_colour' => [
        'Brown',
        'Dark',
        'Doesn’t matter',
        'Fair',
        'Light Brown',
        'Light Dark',
        'Very Fair',
    ],
    'spouse_willing_to_relocate' => [
        'No',
        'Yes',
    ],
    'spouse_living_arrangements' => [
        'Happy to move out at some point after marriage',
        'Prefer to discuss later',
        'Willing to live alone and not with extended family',
        'With family',
    ],
    'spouse_area_choice' => [
        'Anywhere in the UK',
        'Only in East of England',
        'Only in Greater London',
        'Only in North East',
        'Only in North West',
        'Only in South East',
        'Only in South West',
        'Only in West Midlands',
        'Only in Yorkshire & The Humber',
        'Only in Wales',
        'Only in Northern Ireland',
        'Only in Scotland',
    ],
    'spouse_wedding_plan' => [
        'Expensive wedding',
        'Prefer to discuss later',
        'Small nikah in mosque/house/small hall',
        'Average wedding',
    ],
    'wedding_plan' => [
        'Expensive wedding',
        'Prefer to discuss later',
        'Small nikah in mosque/house/small hall',
        'Average wedding',
    ],
];
