<?php
return [
'regions' => [
    [
        'name' => 'Greater London',
        'slug' => 'greater-london',
        'code' => 1.0000,
        'description' => 'Region covering Greater London.',
        'communities' => [
            'Anywhere in Greater London',
            'Barking and Dagenham',
            'Barnet',
            'Bexley',
            'Brent',
            'Bromley',
            'Camden',
            'City of London',
            'City of Westminster',
            'Croydon',
            'Ealing',
            'Enfield',
            'Greenwich',
            'Hackney',
            'Hammersmith and Fulham',
            'Haringey',
            'Harrow',
            'Havering',
            'Hillingdon',
            'Hounslow',
            'Islington',
            'Kensington and Chelsea',
            'Kingston upon Thames',
            'Lambeth',
            'Lewisham',
            'Merton',
            'Newham',
            'Redbridge',
            'Richmond',
            'Southwark',
            'Sutton',
            'Tower Hamlets',
            'Waltham Forest',
            'Wandsworth',
        ],
    ],
    [
        'name' => 'West Midlands',
        'slug' => 'west-midlands',
        'code' => 2.0000,
        'description' => 'Region covering West Midlands.',
        'communities' => [
            'Anywhere in West Midlands',
            'Birmingham',
            'Bromsgrove',
            'Cannock Chase',
            'Coventry',
            'Dudley',
            'East Staffordshire',
            'Herefordshire',
            'Lichfield',
            'Malvern Hills',
            'Newcastle-under-Lyme',
            'North Warwickshire',
            'Nuneaton and Bedworth',
            'Redditch',
            'Rugby',
            'Sandwell',
            'Shropshire',
            'Solihull',
            'South Staffordshire',
            'Stafford',
            'Staffordshire Moorlands',
            'Stoke on Trent',
            'Stratford-on-Avon',
            'Tamworth',
            'Telford and Wrekin',
            'Walsall',
            'Warwick',
            'Wolverhampton',
            'Worcester',
            'Wychavon',
            'Wyre Forest',
        ],
    ],
    [
        'name' => 'East Midlands',
        'slug' => 'east-midlands',
        'code' => 3.0000,
        'description' => 'Region covering East Midlands.',
        'communities' => [
            'Anywhere in East Midlands',
            'Amber Valley',
            'Ashfield',
            'Bassetlaw',
            'Blaby',
            'Bolsover',
            'Boston',
            'Broxtowe',
            'Charnwood',
            'Chesterfield',
            'Derby',
            'Derbyshire Dales',
            'Erewash',
            'Gedling',
            'Harborough',
            'High Peak',
            'Hinckley and Bosworth',
            'Leicester',
            'Lincoln',
            'Mansfield',
            'Melton',
            'Newark and Sherwood',
            'North East Derbyshire',
            'North Kesteven',
            'North Northamptonshire',
            'North West Leicestershire',
            'Nottingham',
            'Oadby and Wigston',
            'Rushcliffe',
            'Rutland',
            'South Derbyshire',
            'South Holland',
            'South Kesteven',
            'West Lindsey',
            'West Northamptonshire',
        ],
    ],
    [
        'name' => 'North West',
        'slug' => 'north-west',
        'code' => 4.0000,
        'description' => 'Region covering North West.',
        'communities' => [
            'Anywhere in North West',
            'Blackburn with Darwen',
            'Blackpool',
            'Bolton',
            'Bury',
            'Cheshire East',
            'Cheshire West and Chester',
            'Cumberland',
            'Halton',
            'Hyndburn',
            'Knowsley',
            'Lancaster',
            'Liverpool',
            'Manchester',
            'Oldham',
            'Pendle',
            'Preston',
            'Ribble Valley',
            'Rochdale',
            'Rossendale',
            'Salford',
            'Sefton',
            'South Ribble',
            'St. Helens',
            'Stockport',
            'Tameside',
            'Trafford',
            'Warrington',
            'West Lancashire',
            'Westmorland and Furness',
            'Wigan',
            'Wirral',
            'Wyre',
        ],
    ],
    [
        'name' => 'North East',
        'slug' => 'north-east',
        'code' => 5.0000,
        'description' => 'Region covering North East.',
        'communities' => [
            'Anywhere in North East',
            'County Durham',
            'Darlington',
            'Gateshead',
            'Hartlepool',
            'Middlesbrough',
            'Newcastle upon Tyne',
            'North Tyneside',
            'Northumberland',
            'Redcar and Cleveland',
            'South Tyneside',
            'Stockton-on-Tees',
            'Sunderland',
        ],
    ],
    [
        'name' => 'East of England',
        'slug' => 'east-of-england',
        'code' => 6.0000,
        'description' => 'Region covering East of England.',
        'communities' => [
            'Anywhere in East of England',
            'Babergh',
            'Basildon',
            'Bedford',
            'Braintree',
            'Brentwood',
            'Breckland',
            'Broadland',
            'Broxbourne',
            'Cambridge',
            'Castle Point',
            'Central Bedfordshire',
            'Chelmsford',
            'City of Peterborough',
            'Colchester',
            'Dacorum',
            'East Cambridgeshire',
            'East Hertfordshire',
            'East Suffolk',
            'Epping Forest',
            'Fenland',
            'Great Yarmouth',
            'Harlow',
            'Hertsmere',
            'Huntingdonshire',
            'Ipswich',
            'King\'s Lynn and West Norfolk',
            'Luton',
            'Maldon',
            'Mid Suffolk',
            'North Hertfordshire',
            'Norwich',
            'South Cambridgeshire',
            'South Norfolk',
            'Southend-on-Sea',
            'St Albans',
            'Stevenage',
            'Tendring',
            'Thurrock',
            'Three Rivers',
            'Uttlesford',
            'Watford',
            'Welwyn Hatfield',
            'West Suffolk',
        ],
    ],
    [
        'name' => 'South East',
        'slug' => 'south-east',
        'code' => 7.0000,
        'description' => 'Region covering South East.',
        'communities' => [
            'Anywhere in South East',
            'Adur',
            'Arun',
            'Ashford',
            'Aylesbury Vale',
            'Basingstoke and Deane',
            'Bracknell Forest',
            'Brighton and Hove',
            'Buckinghamshire',
            'Canterbury',
            'Cherwell',
            'Chichester',
            'Crawley',
            'Dartford',
            'Dover',
            'East Hampshire',
            'Eastbourne',
            'Eastleigh',
            'Elmbridge',
            'Epsom and Ewell',
            'Fareham',
            'Folkestone and Hythe',
            'Gosport',
            'Gravesham',
            'Guildford',
            'Hart',
            'Hastings',
            'Havant',
            'Horsham',
            'Isle of Wight',
            'Lewes',
            'Maidstone',
            'Medway',
            'Mid Sussex',
            'Milton Keynes',
            'Mole Valley',
            'New Forest',
            'Oxford',
            'Portsmouth',
            'Reading',
            'Reigate and Banstead',
            'Rother',
            'Runnymede',
            'Rushmoor',
            'Sevenoaks',
            'Slough',
            'South Oxfordshire',
            'Southampton',
            'Spelthorne',
            'Surrey Heath',
            'Swale',
            'Tandridge',
            'Test Valley',
            'Thanet',
            'Tonbridge and Malling',
            'Tunbridge Wells',
            'Vale of White Horse',
            'Waverley',
            'West Berkshire',
            'West Oxfordshire',
            'Winchester',
            'Windsor and Maidenhead',
            'Woking',
            'Wokingham',
            'Worthing',
        ],
    ],
    [
        'name' => 'South West',
        'slug' => 'south-west',
        'code' => 8.0000,
        'description' => 'Region covering South West.',
        'communities' => [
            'Anywhere in South West',
            'Bath and North East Somerset',
            'Bournemouth, Christchurch and Poole',
            'Bristol',
            'Cheltenham',
            'Cornwall',
            'Cotswold',
            'Dorset',
            'East Devon',
            'Exeter',
            'Forest of Dean',
            'Gloucester',
            'Isles of Scilly',
            'Mid Devon',
            'North Devon',
            'North Somerset',
            'Plymouth',
            'Somerset',
            'South Gloucestershire',
            'South Hams',
            'Stroud',
            'Swindon',
            'Teignbridge',
            'Torbay',
            'Torridge',
            'Tewkesbury',
            'West Devon',
            'Wiltshire',
        ],
    ],
    [
        'name' => 'Yorkshire and the Humber',
        'slug' => 'yorkshire-and-the-humber',
        'code' => 9.0000,
        'description' => 'Region covering Yorkshire and the Humber.',
        'communities' => [
            'Anywhere in Yorkshire and the Humber',
            'Barnsley',
            'Bradford',
            'Calderdale',
            'Doncaster',
            'East Riding of Yorkshire',
            'Kingston upon Hull',
            'Kirklees',
            'Leeds',
            'North East Lincolnshire',
            'North Lincolnshire',
            'North Yorkshire',
            'Rotherham',
            'Sheffield',
            'Wakefield',
            'York',
        ],
    ],
    [
        'name' => 'Wales',
        'slug' => 'wales',
        'code' => 10.0000,
        'description' => 'Region covering Wales.',
        'communities' => [
            'Anywhere in Wales',
            'Cardiff',
            'Newport',
            'Swansea',
            'Other',
        ],
    ],
    [
        'name' => 'Scotland',
        'slug' => 'scotland',
        'code' => 11.0000,
        'description' => 'Region covering Scotland.',
        'communities' => [
            'Anywhere in Scotland',
            'Aberdeen',
            'Dundee',
            'Edinburgh',
            'Glasgow',
            'Other',
        ],
    ],
    [
        'name' => 'Northern Ireland',
        'slug' => 'northern-ireland',
        'code' => 12.0000,
        'description' => 'Region covering Northern Ireland.',
        'communities' => [
            'Belfast',
            'Other',
        ],
    ],
]

];
